export const liveRoles = [
  {
    no: '01',
    roleId: 'REQ-6465',
    recruiter: 'Alex Chen',
    avatar: 'https://i.pravatar.cc/64?img=12',
    client: 'Clyro',
    title: 'Senior AE',
    status: 'offer' as const,
    fee: '£18k',
  },
  {
    no: '02',
    roleId: 'REQ-5665',
    recruiter: 'Sam Ortiz',
    avatar: 'https://i.pravatar.cc/64?img=33',
    client: 'Bloom & Bond',
    title: 'Brand Designer',
    status: 'interview' as const,
    fee: '£12k',
  },
  {
    no: '03',
    roleId: 'REQ-1755',
    recruiter: 'Jordan Lee',
    avatar: 'https://i.pravatar.cc/64?img=52',
    client: 'Forge Analytics',
    title: 'Product Manager',
    status: 'screening' as const,
    fee: '£20k',
  },
]

export const pipelineMix = [
  { name: 'Placed', value: 54, color: '#22c55e' },
  { name: 'Withdrawn', value: 20, color: '#ef4444' },
  { name: 'In process', value: 26, color: '#0061ff' },
]

export const placementSummary = [
  { month: 'May', current: 42000, previous: 31000 },
  { month: 'Jun', current: 38000, previous: 36000 },
  { month: 'Jul', current: 56000, previous: 41000 },
  { month: 'Aug', current: 49000, previous: 47000 },
  { month: 'Sep', current: 68000, previous: 52000 },
  { month: 'Oct', current: 74000, previous: 58000 },
]

export type RoleStatus = (typeof liveRoles)[number]['status']

export const candidates = [
  {
    id: '1',
    name: 'Priya Nair',
    role: 'Brand Designer',
    client: 'Bloom & Bond',
    stage: 'Final interview',
    source: 'LinkedIn',
    score: 92,
    updated: '2h ago',
    avatar: 'https://i.pravatar.cc/64?img=47',
  },
  {
    id: '2',
    name: 'Tom Ellis',
    role: 'Senior AE',
    client: 'Clyro',
    stage: 'Client interview',
    source: 'Referral',
    score: 88,
    updated: '4h ago',
    avatar: 'https://i.pravatar.cc/64?img=15',
  },
  {
    id: '3',
    name: 'Maya Okonkwo',
    role: 'Product Manager',
    client: 'Forge Analytics',
    stage: 'Screening',
    source: 'Indeed',
    score: 81,
    updated: 'Yesterday',
    avatar: 'https://i.pravatar.cc/64?img=32',
  },
  {
    id: '4',
    name: 'Chris Vogel',
    role: 'Full-stack Eng',
    client: 'Northline Group',
    stage: 'First interview',
    source: 'LinkedIn',
    score: 85,
    updated: 'Yesterday',
    avatar: 'https://i.pravatar.cc/64?img=11',
  },
  {
    id: '5',
    name: 'Elena Rossi',
    role: 'Growth Lead',
    client: 'Kinetic Studio',
    stage: 'Sourced',
    source: 'Outbound',
    score: 74,
    updated: '2d ago',
    avatar: 'https://i.pravatar.cc/64?img=45',
  },
  {
    id: '6',
    name: 'James Whitford',
    role: 'Head of Ops',
    client: 'Drift Commerce',
    stage: 'Sourced',
    source: 'LinkedIn',
    score: 79,
    updated: '3d ago',
    avatar: 'https://i.pravatar.cc/64?img=68',
  },
  {
    id: '7',
    name: 'Sofia Mendes',
    role: 'Brand Designer',
    client: 'Bloom & Bond',
    stage: 'Interview',
    source: 'Referral',
    score: 86,
    updated: '5h ago',
    avatar: 'https://i.pravatar.cc/64?img=26',
  },
  {
    id: '8',
    name: 'Omar Haddad',
    role: 'Full-stack Eng',
    client: 'Northline Group',
    stage: 'Screening',
    source: 'GitHub',
    score: 83,
    updated: '1d ago',
    avatar: 'https://i.pravatar.cc/64?img=59',
  },
]

export const openRoles = [
  {
    id: '1',
    title: 'Senior Account Executive',
    client: 'Clyro',
    stage: 'Offer' as const,
    recruiter: 'Alex Chen',
    candidates: 3,
    daysOpen: 64,
    fee: '£18k',
    urgency: 'Critical' as const,
    desk: 'Growth',
  },
  {
    id: '2',
    title: 'Brand Designer',
    client: 'Bloom & Bond',
    stage: 'Interview' as const,
    recruiter: 'Sam Ortiz',
    candidates: 5,
    daysOpen: 34,
    fee: '£12k',
    urgency: 'This month' as const,
    desk: 'Creative',
  },
  {
    id: '3',
    title: 'Growth Lead',
    client: 'Kinetic Studio',
    stage: 'Sourcing' as const,
    recruiter: 'Jordan Lee',
    candidates: 2,
    daysOpen: 18,
    fee: '£22k',
    urgency: 'This month' as const,
    desk: 'Growth',
  },
  {
    id: '4',
    title: 'Product Manager',
    client: 'Forge Analytics',
    stage: 'Screening' as const,
    recruiter: 'Riley Park',
    candidates: 7,
    daysOpen: 52,
    fee: '£20k',
    urgency: 'Critical' as const,
    desk: 'Product',
  },
  {
    id: '5',
    title: 'Full-stack Engineer',
    client: 'Northline Group',
    stage: 'Interview' as const,
    recruiter: 'Morgan Blake',
    candidates: 4,
    daysOpen: 27,
    fee: '£25k',
    urgency: 'Flexible' as const,
    desk: 'Product',
  },
  {
    id: '6',
    title: 'Head of Ops',
    client: 'Drift Commerce',
    stage: 'Sourcing' as const,
    recruiter: 'Alex Chen',
    candidates: 1,
    daysOpen: 11,
    fee: '£28k',
    urgency: 'Flexible' as const,
    desk: 'Ops',
  },
]

export const interviews = [
  {
    id: '1',
    time: '09:30',
    date: 'Today',
    candidate: 'Priya Nair',
    role: 'Brand Designer',
    client: 'Bloom & Bond',
    type: 'Final' as const,
    recruiter: 'Sam Ortiz',
    status: 'Confirmed' as const,
  },
  {
    id: '2',
    time: '11:00',
    date: 'Today',
    candidate: 'Tom Ellis',
    role: 'Senior AE',
    client: 'Clyro',
    type: 'Client' as const,
    recruiter: 'Alex Chen',
    status: 'Confirmed' as const,
  },
  {
    id: '3',
    time: '14:15',
    date: 'Today',
    candidate: 'Maya Okonkwo',
    role: 'Product Manager',
    client: 'Forge Analytics',
    type: 'First' as const,
    recruiter: 'Riley Park',
    status: 'Pending' as const,
  },
  {
    id: '4',
    time: '16:00',
    date: 'Today',
    candidate: 'Chris Vogel',
    role: 'Full-stack Eng',
    client: 'Northline',
    type: 'First' as const,
    recruiter: 'Morgan Blake',
    status: 'Confirmed' as const,
  },
  {
    id: '5',
    time: '10:00',
    date: 'Tomorrow',
    candidate: 'Sofia Mendes',
    role: 'Brand Designer',
    client: 'Bloom & Bond',
    type: 'First' as const,
    recruiter: 'Sam Ortiz',
    status: 'Confirmed' as const,
  },
  {
    id: '6',
    time: '13:30',
    date: 'Tomorrow',
    candidate: 'Omar Haddad',
    role: 'Full-stack Eng',
    client: 'Northline',
    type: 'Client' as const,
    recruiter: 'Morgan Blake',
    status: 'Pending' as const,
  },
]

export const pipelineColumns = [
  {
    id: 'sourced',
    title: 'Sourced',
    color: '#8b919c',
    items: [
      { name: 'Elena Rossi', role: 'Growth Lead', client: 'Kinetic' },
      { name: 'James Whitford', role: 'Head of Ops', client: 'Drift' },
      { name: 'Nina Park', role: 'Perf. Marketer', client: 'Aether' },
    ],
  },
  {
    id: 'screen',
    title: 'Screening',
    color: '#2563eb',
    items: [
      { name: 'Maya Okonkwo', role: 'Product Manager', client: 'Forge' },
      { name: 'Omar Haddad', role: 'Full-stack Eng', client: 'Northline' },
    ],
  },
  {
    id: 'interview',
    title: 'Interview',
    color: '#7c3aed',
    items: [
      { name: 'Chris Vogel', role: 'Full-stack Eng', client: 'Northline' },
      { name: 'Sofia Mendes', role: 'Brand Designer', client: 'Bloom' },
    ],
  },
  {
    id: 'offer',
    title: 'Offer',
    color: '#e85d2a',
    items: [
      { name: 'Priya Nair', role: 'Brand Designer', client: 'Bloom' },
      { name: 'Tom Ellis', role: 'Senior AE', client: 'Clyro' },
    ],
  },
]

export const placements = [
  {
    id: '1',
    hire: 'Amelia Croft',
    role: 'Senior AE',
    client: 'Clyro',
    fee: '£18k',
    start: '15 Sep',
    desk: 'Growth',
    retention: '100%',
  },
  {
    id: '2',
    hire: 'Ben Torres',
    role: 'Brand Designer',
    client: 'Bloom & Bond',
    fee: '£12k',
    start: '1 Oct',
    desk: 'Creative',
    retention: '100%',
  },
  {
    id: '3',
    hire: 'Hannah Cho',
    role: 'Product Manager',
    client: 'Forge Analytics',
    fee: '£20k',
    start: '22 Aug',
    desk: 'Product',
    retention: '100%',
  },
  {
    id: '4',
    hire: 'Luke Brennan',
    role: 'Growth Lead',
    client: 'Kinetic Studio',
    fee: '£22k',
    start: '8 Sep',
    desk: 'Growth',
    retention: '100%',
  },
  {
    id: '5',
    hire: 'Nora Blake',
    role: 'Ops Manager',
    client: 'Drift Commerce',
    fee: '£16k',
    start: '12 Jul',
    desk: 'Ops',
    retention: '100%',
  },
]

export const revenueByDesk = [
  { desk: 'Growth', value: 124000, fill: '#0061ff' },
  { desk: 'Product', value: 98000, fill: '#22c55e' },
  { desk: 'Creative', value: 72000, fill: '#f59e0b' },
  { desk: 'Ops', value: 54000, fill: '#8b5cf6' },
]

export type SettingsSection = {
  id: string
  title: string
  description: string
  fields?: { label: string; value: string }[]
  toggles?: { label: string; on: boolean }[]
  members?: { name: string; role: string; desk: string }[]
}

export const settingsSections: SettingsSection[] = [
  {
    id: 'workspace',
    title: 'Workspace',
    description: 'Agency name, desks, and branding.',
    fields: [
      { label: 'Workspace name', value: 'Jacks Recruitment' },
      { label: 'Plan', value: 'Agency · Pro' },
      { label: 'Timezone', value: 'Europe/London' },
    ],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    description: 'Alerts for interviews, offers, and stale roles.',
    toggles: [
      { label: 'Interview reminders', on: true },
      { label: 'Offer accepted alerts', on: true },
      { label: 'Stale role nudges', on: false },
      { label: 'Weekly digest email', on: true },
    ],
  },
  {
    id: 'team',
    title: 'Team access',
    description: 'Recruiters and desk owners on this workspace.',
    members: [
      { name: 'Alex Chen', role: 'Admin', desk: 'Growth' },
      { name: 'Sam Ortiz', role: 'Recruiter', desk: 'Creative' },
      { name: 'Jordan Lee', role: 'Recruiter', desk: 'Growth' },
      { name: 'Riley Park', role: 'Recruiter', desk: 'Product' },
    ],
  },
]
